export default [
    { id: 0, quest: "Clique para começar a jogar!" },
    { id: 1, quest: "Most likely to be childhood friends with Hiller?" },
    { id: 2, quest: "Who would be the best stripper?" },
    { id: 3, quest: "Who will be the most difficult old person to be around?" },
    { id: 4, quest: "Most likely to join a cult?" },
    { id: 5, quest: "Most likely to ask an overweight woman if she's pregnant?" },
    { id: 6, quest: "In their lifetime, who's most likely to perform sexual acts for money?" },
    { id: 7, quest: "Most likely to have a secret sexual fetish?" },
    { id: 8, quest: "If we were all in prison, who would rise to prison gang leader?" },
    { id: 9, quest: "Most likely to burn down their home for the insurance money?" },
    { id: 10, quest: "Most likely to have a naked picture of themselves on the Internet?" },
    { id: 11, quest: "Who has slept with someone in the shortest amount of time after meeting them?" },
    { id: 12, quest: "Most likely to get too kinky on a first date hookup?" },
    { id: 13, quest: "Who will have the most divorces by the time they're 80?" },
    { id: 14, quest: "Who masturbates the most to former lovers?" },
    { id: 15, quest: "Most likely to secretly run a meth lab?" },
    { id: 16, quest: "Most likely to impregnate someone (or get pregnant) tonight?" },
    { id: 17, quest: "Who would charge the most as a hit man?" },
    { id: 18, quest: "If we were all prostitutes, who would charge the most?" },
    { id: 19, quest: "If a private investigator did a background check on all of us, whose would be the most unsettling?" },
    { id: 20, quest: "If I decided to rob a bank, who's the last person I'd choose to help me?" },
    { id: 21, quest: "Least likely to give up their seat on the bus for an elderly person?" },
    { id: 22, quest: "Most likely to tip less than 10% at a restaurant?" },
    { id: 23, quest: "Who has the best chance of cheating a lie detector test?" },
    { id: 24, quest: "If we were all on Survivor™, who would be the first person voted off the island?" },
    { id: 25, quest: "Most likely to want to build a wall between Mexico and he U.S.?" },
    { id: 26, quest: "Most likely to support polygamy?" },
    { id: 27, quest: "Most likely to become a liability after two drinks?" },
    { id: 28, quest: "Most likely to get a tattoo they will later regret?" },
    { id: 29, quest: "Most likely to steal from their employer?" },
    { id: 30, quest: "Whose funeral will have the smallest attendance?" },
    { id: 31, quest: "Most likely to get upset playing BadPeople?" },
    { id: 32, quest: "If we were all stand-up comedians, who would get the least amount of laughs?" },
    { id: 33, quest: "Most likely to create a scam business?" },
    { id: 34, quest: "In their lifetime, who will have the least positive impact on the human species?" },
    { id: 35, quest: "Most likely to sell out their family and friends for fame?" },
    { id: 36, quest: "Most likely to commit a hit and-run?" },
    { id: 37, quest: "Most likely to follow-through on a revenge plot?" },
    { id: 38, quest: "Whose face looks most like an animal's face?" },
    { id: 39, quest: "Who would be the worst reality TVshow star?" },
    { id: 40, quest: "Who would be the worst phone sex operator?" },
    { id: 41, quest: "Who would _________ for the least amount of money?" },
    { id: 42, quest: "Most likely to appear on the 'NO FLY LIST' ?" },
    { id: 43, quest: "Least likely to tell a new sexual partner that they have an STD?" },
    { id: 44, quest: "Most likely to marry for money?" },
    { id: 45, quest: "Who should be banned from creating offspring?" },
    { id: 46, quest: "Most likely to 'cock block' a friend?" },
    { id: 47, quest: "Most likely to purchase a mail-order wife/husband?" },
    { id: 48, quest: "Who's the last person I'd want to be trapped in an elevator with?" },
    { id: 49, quest: "Who thinks they're more attractive than they actually are?" },
    { id: 50, quest: "Most likely to accidentally shoot themselves?" },
    { id: 51, quest: "Most likely to Facebook® creep a new love interest for several hours?" },
    { id: 52, quest: "Most likely to RSVP 'yes' to a party but never show up?" },
    { id: 53, quest: "Most likely to give a drunk,train wreck speech at a wedding?" },
    { id: 54, quest: "Who has secretly done something VERY illegal and gotten away with it?" },
    { id: 55, quest: "Most likely to murder their spouse for the insurance money andget away with it?" },
    { id: 56, quest: "Who has probably successfully blackmail someone?" },
    { id: 57, quest: "Most likely to turn up drunk to pre-drinks?" },
    { id: 58, quest: "Who takes the most “sick days off” without actually being sick?" },
    { id: 59, quest: "If I decided to kidnap someone, who's the last person I'd ask to help me?" },
    { id: 60, quest: "Most likely to talk their way out of a speeding ticket?" },
    { id: 61, quest: "If I were on Who Wants to Be a Millionaire™, who's the last person I'd call as a life line?" },
    { id: 62, quest: "Least likely to be a target for identity theft?" },
    { id: 63, quest: "Who's least affected by 'save the children' ads?" },
    { id: 64, quest: "Most likely to enter as a contestant on The Bachelor® / The Bachelorette®?" },
    { id: 65, quest: "Least likely to be remembered at a party?" },
    { id: 66, quest: "Who would be the most successful serial killer?" },
    { id: 67, quest: "Most likely to have a midlife crisis?" },
    { id: 68, quest: "Most likely topay for sex?" },
    { id: 69, quest: "Most likely to end up broke due to a gambling addiction?" },
    { id: 70, quest: "Least likely to shave theirgenital area?" },
    { id: 71, quest: "Most likely to appear as a guest on Maury®?" },
    { id: 72, quest: "In their lifetime, who's most likely to be committed to an insane asylum?" },
    { id: 73, quest: "Most likely to get fired for _________ ?" },
    { id: 74, quest: "Who's the most high maintenance in a relationship?" },
    { id: 75, quest: "Least likely to sacrifice their life for a family member?" },
    { id: 76, quest: "If we were all homeless panhandlers,who would make the least amount of money?" },
    { id: 77, quest: "In their lifetime, who will most likely need a liver transplant?" },
    { id: 78, quest: "If everyone committed _________ , who would be the last person to get caught?" },
    { id: 79, quest: "Most likely to enjoy being dominated in the bedroom?" },
    { id: 80, quest: "Most likely to show up to anEmergencyRoom with a _________ up their ass?" },
    { id: 81, quest: "Most likely to go ___________ with Donald Trump?" },
    { id: 82, quest: "Most likely to fall for a pyramid scheme?" },
    { id: 83, quest: "Who was thelast person topiss on a sexual partner?" },
    { id: 84, quest: "If a big fire broke out right now,who would push everyone out of the way to get out first?" },
    { id: 85, quest: "Most likely to become a vegetarian because their partner wanted them to?" },
    { id: 86, quest: "Most likely to try ____________ with Charlie Sheen?" },
    { id: 87, quest: "Least likely to try _____________ ?" },
    { id: 88, quest: "Who will be the next person tohave a threesome?" },
    { id: 89, quest: "Most likely to join ISIS?" },
    { id: 90, quest: "Most likely to break up with someone because __________ ?" },
    { id: 91, quest: "If we were all therapists, who would probably sleep with their patients?" },
    { id: 92, quest: "Who would be the worst person to work for?" },
    { id: 93, quest: "Who was the last person to masturbate?" },
    { id: 94, quest: "Least likely to end a relationship with someone if they __________ ?" },
    { id: 95, quest: "Most likely to become a liability after eating a pot brownie?" },
    { id: 96, quest: "Least likely to send a sex tape?" },
    { id: 97, quest: "Who has seen the most people in this room naked?" },
    { id: 98, quest: "Who has hada sexualdream about ____________ ?" },
    { id: 99, quest: "Who could never say no to _____________ ?" },
    { id: 100, quest: "In their lifetime, who's most likely to become a pimp or madam?" },
    { id: 101, quest: "Most likely tohave had sexin the back of ataxi?" },
    { id: 102, quest: "Who has done the most 'walks of shame' ?" },
    { id: 103, quest: "Least likely to believe in global warming?" },
    { id: 104, quest: "Who is most like their racial stereotype?" },
    { id: 105, quest: "Who would get the most enjoyment from being a member of the opposite sex for a day?" },
    { id: 106, quest: "Most likely to lie to someone to get something they want?" },
    { id: 107, quest: "Who would sell their soul for the least amount of money?" },
    { id: 108, quest: "Most likely to fake an orgasm?" },
    { id: 109, quest: "If I was the ruthless dictator of a country, who would I choose as my second in-command?" },
    { id: 110, quest: "Most likely to convince the group to play strip poker?" },
    { id: 111, quest: "They say, 'You Can't judge a book by its cover.' Who did I misread when we first met?" },
    { id: 112, quest: "Most likely to 'not get the joke' ?" },
    { id: 113, quest: "Most likely to cheat while playing aboard game?" },
    { id: 114, quest: "Who has the largest porn collection?" },
    { id: 115, quest: "Most likely to crack a beer during a eulogy?" },
    { id: 116, quest: "Most likely to laugh if they saw a blindperson trip?" },
    { id: 117, quest: "Most likely to say, 'I'm not racist, but ... ' ?" },
    { id: 118, quest: "Most likely to fart and blame it on someone else?" },
    { id: 119, quest: "Most likely to shout the wrong name during sex?" },
    { id: 120, quest: "Who has had sex in the most random place?" },
    { id: 121, quest: "Who is the worst person to call for relationship advice?" },
    { id: 122, quest: "Most likely to have sex with a homeless guy because they though the was a hipster?" },
    { id: 123, quest: "Who would tattoo a teardrop on their face for the least amount of money?" },
    { id: 124, quest: "Most likely to end up on the FBI's Most Wanted List?" },
    { id: 125, quest: "Most likely to steal from a tip jar?" },
    { id: 126, quest: "Most likely to create a fake social media account to spy on someone?" },
    { id: 127, quest: "Who has gone the longest without showering?" },
    { id: 128, quest: "Most likely tomorrow something with no intention of returning it?" },
    { id: 129, quest: "Who is 'never the problem' in a relationship ?" },
    { id: 130, quest: "Who really needs to start making NewYear's resolutions?" },
    { id: 131, quest: "Who would be the easiest to kidnap?" },
    { id: 132, quest: "Most likely to lie on their resume?" },
    { id: 133, quest: "Who was the oldest person to lose their virginity?" },
    { id: 134, quest: "Most likely to leave a party by blowing glitter in your face and disappearing?" },
    { id: 135, quest: "Who would take the longest to be reported to the police asmissing?" },
    { id: 136, quest: "Who has the worst 'game' ?" },
    { id: 137, quest: "Most likely to shed the next drunken tear?" },
    { id: 138, quest: "Most likely to accidentally have drugs on them while going through airport security?" },
    { id: 139, quest: "Most likely to draw a dick on passed out friend?" },
    { id: 140, quest: "Who was the last person to have a drink thrown in their face?" },
    { id: 141, quest: "Who was the last person to be drunk/high at work?" },
    { id: 142, quest: "Most likely to say 'I love you' too early ?" },
    { id: 143, quest: "Most likely to wake up tomorrow not knowing where they are?" },
    { id: 144, quest: "Who has the worst poker face?" },
    { id: 145, quest: "If we were all police officers, who would be the dirty cop?" },
    { id: 146, quest: "Most likely to run into a former lover and not remember their name?" },
    { id: 147, quest: "Who can't go 10 minutes without looking at themselves in the mirror?" },
    { id: 148, quest: "Most likely to eat me out if they were under pressure from the cops?" },
    { id: 149, quest: "If we were all characters in a horror movie,who would get killed first?" },
    { id: 150, quest: "Most likely to sleep their way to the top?" },
    { id: 151, quest: "Most likely to puke and rally?" },
    { id: 152, quest: "Most likely to have a secret body piercing or tattoo?" },
    { id: 153, quest: "Most likely to have a secret sex tape?" },
    { id: 154, quest: "Most likely to sleep with co-worker?" },
]